version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  test_db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: test_bike_gps
    ports:
      - "5434:5432"
    volumes:
      - pgtestdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    # restart: always

volumes:
  pgdata:
  pgtestdata:
